name: nf
channels:
 - bioconda
 - conda-forge
 - defaults
dependencies:
 - zstd<=1.3.3
 - awscli>=1.15.16
 - perl>=5.16.0
 - perl-biox-seq
 - perl-ms
 - perl-app-cpanminus
 - perl-yaml-tiny
 - openms
 - flashlfq
 - bioconductor-msnbase
 - fido
 - msgf_plus
